package scripts.MontsTanner;

import scripts.MontsTanner.utils.Variables;

public class Gui extends javax.swing.JFrame {
	
    /**
	 * 
	 */
	private static final long serialVersionUID = 3032808224792670345L;
	/**
     * Creates new form NewJFrame
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MontsTanner");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leather", "Soft-leather", "Green dragon leather", "Blue dragon leather", "Red dragon leather", "Black dragon leather" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Leather to make");

        jCheckBox2.setText("Use Super Energy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jButton1)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>                        

                                    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { 
    	if(jCheckBox2.isSelected()) {
    		Variables.get().superEnergy = true;
    	} else {
    		Variables.get().superEnergy = false;
    	}
    	hideChoice(); 
    	dispose(); 
    } 
    
    private void hideChoice() { 
    	Variables.get().leather = (jComboBox1.getSelectedItem().toString()); 
    	switch (Variables.get().leather) { 
    	case "Leather": Variables.get().hide = "Cowhide"; 
    	Variables.get().coinsToMake = 1; 
    	Variables.get().child = 108; 
    	break; 
    	case "Hard leather": 
    		Variables.get().hide = "Cowhide"; 
    		Variables.get().coinsToMake = 3; 
    		Variables.get().child = 109; 
    		break; 
    	case "Green dragon leather": 
    		Variables.get().hide = "Green dragonhide"; 
    		Variables.get().coinsToMake = 20; 
    		Variables.get().child = 112; 
    		break; 
    	case "Blue dragon leather": 
    		Variables.get().hide = "Blue dragonhide"; 
    		Variables.get().coinsToMake = 20; 
    		Variables.get().child = 113; 
    		break; 
    	case "Red dragon leather": 
    		Variables.get().hide = "Red dragonhide"; 
    		Variables.get().coinsToMake = 20; 
    		Variables.get().child = 114; 
    		break; 
    	case "Black dragon leather":
    		Variables.get().hide = "Black dragonhide"; 
    		Variables.get().coinsToMake = 20; 
    		Variables.get().child = 115; 
    		break; 
    	} 
    	return; 
    }
                                            
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration                   
}
