package scripts.MontsTiaraCrafter;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import org.tribot.api2007.types.RSTile;

import scripts.MontsTiaraCrafter.utils.Variables;

/**
 *
 * @author User
 */
public class TiaraCrafterGui extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form TiaraCrafterGui
     */
    public TiaraCrafterGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Monts Tiara Crafter");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Air", "Mind", "Water", "Earth", "Fire", "Body" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tiara to create:");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Set Mouse Speed");

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMaximum(150);
        jSlider1.setMinimum(70);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel3)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>          
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        tiaraChooser();
        dispose();
   
    }         

	    private void tiaraChooser() {
	    	Variables.get().tiaraToCraft = jComboBox1.getSelectedItem().toString();
	    	Variables.get().mouseSpeed = jSlider1.getValue();
	    	
	    	switch(Variables.get().tiaraToCraft) {
	    	
	    	case "Air":		
	    		RSTile[] airAltarPath = {new RSTile(3012, 3357), new RSTile(3012, 3358), new RSTile(3010, 3359), new RSTile(3007, 3358),  
	    			new RSTile(3006, 3355), new RSTile(3006, 3352), new RSTile(3007, 3349), new RSTile(3007, 3346), 
	    			new RSTile(3007, 3344), new RSTile(3007, 3341), new RSTile(3007, 3338), new RSTile(3007, 3335), 
	    			new RSTile(3007, 3332), new RSTile(3006, 3329), new RSTile(3006, 3326), new RSTile(3006, 3323), 
	    			new RSTile(3005, 3320), new RSTile(3002, 3318), new RSTile(3000, 3315), new RSTile(2999, 3312), 
	    			new RSTile(2997, 3309),new RSTile(2995, 3307), new RSTile(2993, 3304), new RSTile(2991, 3302), 
	    			new RSTile(2991, 3299), new RSTile(2991, 3295),new RSTile(2989, 3292), new RSTile(2987, 3292)};
	    			
	    			Variables.get().altarPath = airAltarPath;
		    		Variables.get().talismanNeeded = "Air talisman";
	    			break;
	    	
	    	case "Mind":
				 RSTile[] mindAltarPath = {new RSTile(2946, 3369), new RSTile(2946, 3370), new RSTile(2946, 3373), new RSTile(2948, 3376),	
				 new RSTile(2952, 3379), new RSTile(2956, 3382),	new RSTile(2960, 3382), new RSTile(2964, 3385),	new RSTile(2966, 3389), 
				 new RSTile(2965, 3393),	new RSTile(2967, 3398), new RSTile(2968, 3402),	new RSTile(2971, 3407), new RSTile(2974, 3410),
				 new RSTile(2977, 3413), new RSTile(2981, 3416),	new RSTile(2984, 3418), new RSTile(2987, 3420),	new RSTile(2988, 3424), 
				 new RSTile(2988, 3429), new RSTile(2986, 3433), new RSTile(2983, 3436),	new RSTile(2981, 3441),new RSTile(2980, 3445), 
				 new RSTile(2977, 3449),	new RSTile(2976, 3453), new RSTile(2973, 3457),	new RSTile(2972, 3462),new RSTile(2973, 3467),
				 new RSTile(2974, 3470),new RSTile(2972, 3475),	new RSTile(2973, 3478),new RSTile(2975, 3481),new RSTile(2976, 3485),
				 new RSTile(2978, 3487),new RSTile(2982, 3491), new RSTile(2980, 3500), new RSTile(2980, 3503),	new RSTile(2979, 3508),
				 new RSTile(2980, 3513)};
				 
				 Variables.get().altarPath = mindAltarPath;
		    	Variables.get().talismanNeeded = "Mind talisman";
				 break;
				 
			case "Body":
				RSTile[] bodyAltarPath = {new RSTile(3093, 3491),new RSTile(3090, 3491),new RSTile(3088, 3489),new RSTile(3086, 3486),new RSTile(3084, 3485),
				new RSTile(3081, 3482),new RSTile(3081, 3478),new RSTile(3081, 3474),new RSTile(3081, 3471),new RSTile(3081, 3467),new RSTile(3083, 3465),
				new RSTile(3087, 3463),new RSTile(3085, 3460),new RSTile(3083, 3457),new RSTile(3081, 3455),new RSTile(3081, 3450),new RSTile(3079, 3448),
				new RSTile(3075, 3447),new RSTile(3073, 3444),new RSTile(3073, 3440),new RSTile(3070, 3441),new RSTile(3067, 3440),new RSTile(3063, 3439),
				new RSTile(3059, 3440),new RSTile(3055, 3443)};
				
				Variables.get().altarPath = bodyAltarPath;	
		    	Variables.get().talismanNeeded = "Body talisman";
				break;
				
			case "Earth":
				RSTile[] earthAltarPath = {new RSTile(3254, 3420),new RSTile(3254, 3423),new RSTile(3255, 3427),new RSTile(3260, 3428),new RSTile(3265, 3428),
				new RSTile(3271, 3428),new RSTile(3277, 3428),new RSTile(3283, 3429),new RSTile(3287, 3433),new RSTile(3290, 3437),new RSTile(3291, 3442),
				new RSTile(3291, 3447),new RSTile(3292, 3452),new RSTile(3294, 3458),new RSTile(3295, 3462),new RSTile(3297, 3466),new RSTile(3300, 3469),
				new RSTile(3304, 3472)};
	
				Variables.get().altarPath = earthAltarPath;
		    	Variables.get().talismanNeeded = "Earth talisman";
				break;
				
			case "Fire":
				RSTile[] fireAltarPath = {new RSTile(3269, 3167),new RSTile(3272, 3167),new RSTile(3276, 3168),new RSTile(3276, 3172),new RSTile(3278, 3176),
				new RSTile(3279, 3179),new RSTile(3284, 3180),new RSTile(3289, 3183),new RSTile(3292, 3186),new RSTile(3294, 3190),new RSTile(3297, 3196),
				new RSTile(3301, 3199),new RSTile(3301, 3204),new RSTile(3302, 3210),new RSTile(3302, 3215),new RSTile(3302, 3219),new RSTile(3302, 3223),
				new RSTile(3302, 3227),new RSTile(3304, 3233),new RSTile(3306, 3239),new RSTile(3307, 3244),new RSTile(3309, 3249),new RSTile(3312, 3253)};
			
				Variables.get().altarPath = fireAltarPath;
		    	Variables.get().talismanNeeded = "Fire talisman";
				break;
		
				
			case "Water":
				RSTile[] waterAltarPath = {new RSTile(3093, 3244),new RSTile(3093,3249), new RSTile(3099,3246), new RSTile(3101, 3236),new RSTile(3110,3228), new RSTile(3120, 3225),
				new RSTile(3124,3220),
				new RSTile(3136, 3218),new RSTile(3139, 3209),new RSTile(3142, 3198),new RSTile(3148, 3190),new RSTile(3158, 3183),new RSTile(3164, 3172),
				new RSTile(3172, 3161),new RSTile(3182, 3163)};

				Variables.get().altarPath = waterAltarPath;
		    	Variables.get().talismanNeeded = "Water talisman";
				break;		
	    		
	    	}
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JComboBox<String> jComboBox1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JSlider jSlider1;
	    // End of variables declaration        

}
